### ISSUE TITLE
Can't start proxy with custom port when using image from Docker Hub

### ISSUE THREAD

**Issue by weendigo** [autifyhq/docker-browserup-proxy#2]
Hi, 
thank you, your docker image is very useful. 
However, I've encountered a problem that I'm unable to start proxy with a custom port.

The basic POST call for default ports work just fine, e.g.:
**curl -X POST http://{address}:8010/proxy** 
returns expected **{"port":8085}**                                                       

OTOH, the call that should start proxy on custom port:
**curl -X POST -d 'port=8099' http://{address}:8010/proxy**
produces following response:

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /proxy. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.NoClassDefFoundError: Could not initialize class org.mvel2.util.ParseTools
        at org.mvel2.PropertyAccessor.set(PropertyAccessor.java:249)
        at org.mvel2.PropertyAccessor.set(PropertyAccessor.java:135)
        at org.mvel2.MVEL.setProperty(MVEL.java:1088)
        at com.google.sitebricks.MvelEvaluator.write(MvelEvaluator.java:64)
        at com.google.sitebricks.binding.MvelRequestBinder.bind(MvelRequestBinder.java:79)
        at com.google.sitebricks.routing.WidgetRoutingDispatcher.bindAndReply(WidgetRoutingDispatcher.java:97)
        at com.google.sitebricks.routing.WidgetRoutingDispatcher.dispatch(WidgetRoutingDispatcher.java:88)
        at com.google.sitebricks.DebugModeRoutingDispatcher.dispatch(DebugModeRoutingDispatcher.java:56)
        at com.google.sitebricks.SitebricksFilter.doFilter(SitebricksFilter.java:62)
        at com.google.sitebricks.HiddenMethodFilter.doFilter(HiddenMethodFilter.java:70)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:494)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
        at java.base/java.lang.Thread.run(Thread.java:830)
</pre>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.20.v20190813</a><hr/>

</body>
</html>

**Comment by doublemarket** [comment]
@weendigo Thank you for reporting the issue with the detailed information! As the exception you pasted suggests, it is caused by a library `mvel` which browserup-proxy is internally using. The mvel doesn't support newer JDKs while the container uses openjdk14. This is reported in #1 and it's trying to solve this issue by downgrading the JDK. We're now working on fixing the issue so please stay tuned.

**Comment by doublemarket** [comment]
@weendigo The container image with browserup-proxy 2.0.1 and JDK8 has been published in [Docker Hub](https://hub.docker.com/layers/autifyhq/browserup-proxy/2.0.1-jdk8/images/sha256-50a3d323e0d80de2bd140e301bd3962b7aababe18a9c60267281802d7614f944?context=explore). Please use this image instead until the issue is solved in browserup-proxy. Thanks!
